before:
  hooks:
    - go mod tidy
    - go generate ./cmd/gopom
builds:
  - goos:
      - linux
    goarch:
      - amd64
    binary: gopom
    main: ./cmd/gopom/main.go
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
