language: go
matrix:
  include:
    - os: linux
      dist: xenial
      go: 1.13.x
      install:
        sudo apt-get install -y libasound2-dev
    - os: osx
      go: 1.13.x
  fast_finish: true

script:
  - make build
env:
  global:
    - GO111MODULE=on